### ISSUE TITLE
Update !iss parser to include a link

### ISSUE THREAD

**Issue by chelming** [ServiceNowDevProgram/SlackerBot#168] opened 2022-10-13 12:53 UTC
Using [block-kit-builder](https://app.slack.com/block-kit-builder) it should be possible to include a link to the location in google maps so you can browse the map when it's in the middle of an ocean and you don't know where it is.

**Comment by wiz0floyd** [comment] 2022-10-13 12:55
Duplicate of #167, but I'll close #167 since this has a link to block-kit-builder :/

**Closed** 2023-10-03 04:30 UTC
